### ISSUE TITLE
Can't use file selector with Flatpak install and i3 window manager

### ISSUE THREAD

**Issue by TheUserCreated** [borgbase/vorta#1024]
**Describe the bug**
The exact same bug as shown in issue no. #693 , but in *every* place where one might select a directory (repository selection, mount point selection for mounting archives, add folder menu for what to back up). I am on version 0.7.7 installed via flatpak.
It may be worth noting that when I change to a gnome session on the same machine, the issue does not seem to occur

**To Reproduce**
Start an i3 session with vorta installed via flatpak.
1. Attempt to select a new repository
2. Navigate to your folder of choice
3. Notice the lack of ability to select anything but *files*

**Environment (please complete the following information):**
- OS: Arch Linux
- Vorta version: 0.7.7
- Installed from: Flatpak

[vorta.log](https://github.com/borgbase/vorta/files/6698785/vorta.log)

Quick edit; I did a bit more testing and it seems that in my setup at least, this issue does *not* occur with the version of vorta installed from the AUR

**Comment by m3nu** [comment]
Nothing stands out in the logs. Not sure we can change any code in Vorta to make this work. The file selector is provided by Qt and the OS. 😬

**Comment by TheUserCreated** [comment]
I figured as much, but wanted to open an issue since it seemed to only occur under certain circumstances even on the exact same machine (only in certain WM, only in flatpak). But if there isn't anything that can be done here to fix it, then I'll go ahead and close the issue. Thanks for the info though :p

**Comment by m3nu** [comment]
We can still leave it open. Maybe someone can share more information, if others encounter the same problem.

**Comment by bastiencyr** [comment]
Hello, 
I can reproduce this bug on my machine. I think that some of this weird behaviours may be related to the four tests that don't pass in my setup.  
 I don't have kde but cinnamon so I dont think it's related to Kde since cinnamon is based on Gnome. 
 I have this following bug : 
  - can't input a password with 8 chars
  - same error : "Please enter a valid repo URL or select a local path" when I try to paste a repository path 
 
 I don't have any issue with file selector and I didn't test i3. 
 
 I will take a look on code to pass tests on Cinnamon. I hope that this will resolved some bugs on kde. 
 Since I'm already on PR, I'll wait a bit before looking.
