### ISSUE TITLE
order of items in progress display should be same as in borg

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#1055]
Vorta displays the progress indication in a different order than borg.

The logical order for the sizes is like: original > compressed > deduplicated.

Whether the files count comes first or last doesn't matter, but I would suggest using same position as in `borg create --progress`.

**Comment by m3nu** [comment]
Yeah, I was wondering about this too. Should change for consistency.

**Comment by bastiencyr** [comment]
It will be impossible to keep this text area with #1045. If backups are runned concurrently, output is a mess because all is printed in the same area. Informations will alternate between one and then another bachup and then one...  A hidden terminal area can partially solve this but informations will be mix anyway. 

 I don't have solution. We can keep this text area for the moment and find a solution after.

**Comment by m3nu** [comment]
Fixed in current master.
