### ISSUE TITLE
Vorta not in repository of Ubuntu 20.04

### ISSUE THREAD

**Issue by miltonh26** [borgbase/vorta#1068]
Hi Borgbase, 

Vorta is only available as a flatpak which does not allow accessing another device to backup to. Tried the flatpak switch --devices=all and pointing to the device mounted folder, both did not work. 

Unable to build Volta because python-virtualenv is no longer in the 20.04 repository. 

Any suggestions on how to make this work? 

It would be great to have Vorta available as a debian file in the repository. 

Thanks.

**Comment by bastiencyr** [comment]
Hello, 
Vorta is in repository of ubuntu 21 and Debian 11. It will be in ubuntu 22 too.

**Comment by sten0** [comment]
Hi @miltonh26,

The latest available version of Vorta in Ubuntu repositories is almost certainly backportable to 20.04 :-)  There are instructions at the following URL, along with the protocol for requesting backports if you'd rather hopefully wait for someone else to do the work:  https://wiki.ubuntu.com/UbuntuBackports

@samuel-w, are you interested in resurrecting your PPA to support 20.04 LTS users until 22.04 is released?

**Comment by samuel-w** [comment]
No, I don't even use Ubuntu anymore. Anyone's welcome to start their own PPA though, Debian files here https://gist.github.com/samuel-w/0421502113f8bf43296c1f74cef57b48

**Comment by sten0** [comment]
samuel-w ***@***.***> writes:

> No, I don't even use Ubuntu anymore.

Oh!  If you feel like sharing what you switched to, I'm curious to know :-)

> Anyone's welcome to start their own PPA though, Debian files here https://gist.github.com/samuel-w/0421502113f8bf43296c1f74cef57b48
>

Thank you for sharing, and thanks again for the time you spent
maintaining that PPA!  I guess in the interest of making this maximally
easy for an individual (rather than PPA maintainer), here is the
work-flow for a one-off Ubuntu rebuild of the newest Debian version (at
this time):

dget http://deb.debian.org/debian/pool/main/v/vorta/vorta_0.7.8-1.dsc
cd vorta-0.7.8
sudo apt build-dep ./
dch -i
# /\ According to https://manpages.ubuntu.com/manpages/focal/man1/dch.1.html
# this will add the correct ~ubuntu0 version suffix, which is needed for
# smooth upgrades
dpkg-buildpackage -us -uc
sudo dpkg -i ../vorta_0.7.8*.deb

Updating to a new version and/or resyncing with Debian is a more
involved process with more than one solution.  Oh, by the way, I didn't
check if Ubuntu Focal has the prerequisite dependencies for 0.7.8.  If
it needs a newer version of a dependency, then I'd probably wait for
Ubuntu 22.04 (or upgrade to 21.10), because manually updating those deps
may break already-installed software.

**Comment by renyhp** [comment]
> dget http://deb.debian.org/debian/pool/main/v/vorta/vorta_0.7.8-1.dsc
> cd vorta-0.7.8
> sudo apt build-dep ./
> dch -i
> # /\ According to https://manpages.ubuntu.com/manpages/focal/man1/dch.1.html
> # this will add the correct ~ubuntu0 version suffix, which is needed for
> # smooth upgrades
> dpkg-buildpackage -us -uc
> sudo dpkg -i ../vorta_0.7.8*.deb

Thanks for sharing this! Sadly, the Debian repository is also not up to date...

**Comment by m3nu** [comment]
@sten0 was working on adding version 0.8.x to Debian. I had to update some tests and removed some outdated dependencies here: https://salsa.debian.org/python-team/packages/vorta/-/merge_requests/1

Once he is happy with the changes, we'll release them as v0.8.3.

**Comment by sten0** [comment]
@renyhp, you're welcome!

Unfortunately 100% of 0.8.x's unit tests are failing in up-to-date
Debian sid/unstable chroots and containers.  When this has been resolved
a new release will be uploaded and real-world testing can commence :-)
Before that, I don't believe that an upload satisfies the high
expectations of Debian users.  Also, now that the holidays are hover,
progress can resume!

**Comment by sten0** [comment]
@renyhp

Vorta has been in a good state to backport (or start an Ubuntu PPA) since
11 Feb.  Sorry I forgot to update this bug until now.

Without further replies I will allow the stale bot to do its thing
