### ISSUE TITLE
[RFC] Stable Vorta version with Python 3.10 support: A cherry pick away?

### ISSUE THREAD

**Issue by sten0** [borgbase/vorta#1133]
Hi,

Debian sid/unstable has begun its Python 3.9 to 3.10 transition and Vorta 0.7.8 isn't ready (https://bugs.debian.org/1001490).  Options at the moment appear to be:
1. Update to 0.8.2 (Is the 0.8.x series ready yet, or is it still too early?)
2. Cherry pick c7a1077fec022d60ad27919f60199424f9f13e6a (Is this commit self-contained?  Do you think this is a riskier option than the first?)

Both options introduce regression potential, and packages in Debian sid/unstable are supposed to be suitable for a stable release (as opposed to the Debian experimental suite).  Also, sid/unstable is where Ubuntu syncs its packages from--even for LTS releases.

What do you think?
Nicholas

**Comment by m3nu** [comment]
The 0.8 branch has been out for a while now (for macOS, Flatpak and PyPi) and no real issues were reported. I also use it all the time. So I can in good faith recommend it as a stable release.

I don't think 0.7.x can be made to work properly with Py3.10 because it relies on APScheduler, which removed Qt support and the [older versions](https://github.com/agronholm/apscheduler/blob/3.x/setup.py#L23) don't work on Py3.10. That's the biggest issue: If Debian ships with a [newer APScheduler version](https://github.com/agronholm/apscheduler/blob/master/setup.cfg#L17) (to support Py3.10, it won't include Qt support, which we need. This was the main reason for dropping the dependency.

**Comment by sten0** [comment]
Hi Manu!

Manu ***@***.***> writes:

> The 0.8 branch has been out for a while now (for macOS, Flatpak and PyPi) and no real issues were reported. I also use it all the time. So I can in good faith recommend it as a stable release.
>

That's wonderful news :-)

> I don't think 0.7.x can be made to work properly with Py3.10 because it relies on APScheduler, which removed Qt support and the [older versions](https://github.com/agronholm/apscheduler/blob/3.x/setup.py#L23) don't work on Py3.10. That's the biggest issue: If Debian ships with a [newer APScheduler version](https://github.com/agronholm/apscheduler/blob/master/setup.cfg#L17) (to support Py3.10, it won't include Qt support, which we need. This was the main reason for dropping the dependency.
>

Ok, it sounds like the fix isn't fully contained in c7a1077 and it will
be better to just switch to 0.8.2.  I'm hoping someone on the Python
Team has time, because it doesn't seem like I will until
2022--0.8.2+Python 3.10 is a non-trivial update that currently FTBFS on
Debian infrastructure.

If we don't get in touch before then,
Merry Christmas and Happy New Year!
Regards,
Nicholas

**Comment by sten0** [comment]
Unfortunately 0.8.2 plus cherry picked commits to bring it to the level of 23c4767 fails 100% of its unit tests in an up-to-date Debian sid/unstable clean chroot or container.

[vorta_0.8.2-1_amd64-2022-01-23T04:07:09Z.build.txt](https://github.com/borgbase/vorta/files/7919746/vorta_0.8.2-1_amd64-2022-01-23T04.07.09Z.build.txt)

**Comment by sten0** [comment]
Closing since the discussion is taking place in other threads
