### ISSUE TITLE
FR: Local config mode for development.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1162]
When I start *vorta* from my local python environment, it will always use the global settings and config files. I feel very uneasy when sharing the config files of my real backup system with development versions and branches. This can get especially problematic when a new version uses a different config setup or file format. I also see a problem for manual (and possibly automatic) testing.

A solution would be the option to call *vorta* with an command-line argument like `--local` that starts it in a local config mode. In this mode vorta would not use the user wide location for config files but one nearby *(e.g. in the cwd)*.

**Comment by m3nu** [comment]
The only config file we use is the database. I usually just make a copy of it and copy it back after done playing around. `settings.sqlite` in your Vorta folder (precise location varies by OS)

**Comment by m3nu** [comment]
Or for full isolation, use a VM. I use them regularly to do testing with Linux desktops.

Else it will be hard to fully isolate everything. Since you will still want to use some Borg repo or source files.

**Comment by real-yfprojects** [comment]
> Or for full isolation, use a VM. I use them regularly to do testing with Linux desktops.

That was a very good tip. I use a Virtualbox now.

**Comment by ratchek** [comment]
Hi,
I unfortunately can't use Virtualbox for this and I think a developer mode would be a nice addition and would make me feel easier in general. Can we reopen this issue and I'd take a crack at it?

**Comment by real-yfprojects** [comment]
> I think a developer mode would be a nice addition and would make me feel easier

I agree. Currently I always have to jump back and forth between the VM and my dev environment.

**Comment by ratchek** [comment]
Now that I'm looking at the code, it seems like the expected behavior of a --development mode should be not just to localize the settings database, but also the log, cache, and temp directories. So I'm thinking that whenever the program is called with a --development flag, the code should just override the directories supplied by appdirs in the config file and instead put all of them in a folder somewhere in the project tree. 
Does that seem like a sane approach?

**Comment by real-yfprojects** [comment]
> Does that seem like a sane approach?

I agree, this would be a good way of implementing the dev mode.

**Comment by real-yfprojects** [comment]
Vorta could even look for a specific file/folder in the cwd, so that developer doesn't always have to pass the flag. It could use `pyproject.toml` like other dev tools.

**Comment by ratchek** [comment]
This is a great idea, but I think I'll separate this into two separate pull requests if that's ok.

**Comment by ratchek** [comment]
Hi, I have the following problem when implementing the feature and would appreciate your thoughts.

Like previously discussed, the best place to set the local folder if the development flag is enabled would be the vorta.config file.
To check if the development flag is enabled I need to import parse_args from vorta.utils.
But vorta.utils imports from vorta.logger, which uses the LOG_DIR from the vorta.config file. So it's a circular dependency.

Here are possible solutions to this problem I managed to come up with:
1. parse_args in the utils file doesn't actually use the logger. So extract it to a separate file. (This wouldn't be horrible, because it only gets called a handful of times and I don't think that refactoring would be a big job. But it adds an extra file)
2. Move parse_args to the config file (Same considerations as point 1 regarding refactoring).
3. Is there maybe any way to tell python to not import ALL the imports in the utils file when importing parse_args? That seems like it adds unnecessary complexity to the code, but maybe there's an elegant solution in Python that I'm not aware of.

Which solution do you think works best? And did I miss any ways to attack this problem?

**Comment by real-yfprojects** [comment]
> the best place to set the local folder if the development flag is enabled would be the vorta.config file

Do you mean the `vorta.config` module?

> Which solution do you think works best? And did I miss any ways to attack this problem?

This is what I thought about: When a specific flag is set in the commandline (these flags are parsed by `parse_args`) the LOG_DIR and co. variables are overwritten.

> Is there maybe any way to tell python to not import ALL the imports in the utils file when importing parse_args? That seems like it adds unnecessary complexity to the code, but maybe there's an elegant solution in Python that I'm not aware of.

An easy way of resolving circular imports is using `import module` instead of `from module import object`. The latter allows python to defer the actual import. However you shouldn't call `parse_args` from `vorta.config` this makes life harder in the future I think.

**Comment by ratchek** [comment]
> Do you mean the vorta.config module?
Yes.

Ok,so just to make sure I understand: I should check for the flag and override the storage variables in the __main__ file?

Two follow-up questions:
Wouldn't that mean that in some cases (like when an error occurs during the call to exception_handler in line 40) the relevant log files would still be in the system folders instead of the local folders despite the fact that the --development flag was included? I know it's an extreme edge case, but doesn't that have the potential for confusion?

And would you mind elaborating on why I shouldn't call parse_args from vorta.config? (I'm new to writing code for larger projects, so I 100% believe that you're correct. I just want to learn what sort of problems this could create in the future so I don't make that mistake again).

**Comment by real-yfprojects** [comment]
> I should check for the flag and override the storage variables in the main file?

That's my suggestion.

> Wouldn't that mean that in some cases (like when an error occurs during the call to exception_handler in line 40) the relevant log files would still be in the system folders instead of the local folders despite the fact that the --development flag was included? I know it's an extreme edge case, but doesn't that have the potential for confusion?

The file logging is setup in this line:
https://github.com/borgbase/vorta/blob/bcc126b6347ec4825e119bde834873fee9c2965d/src/vorta/__main__.py#L57

> And would you mind elaborating on why I shouldn't call parse_args from vorta.config? (I'm new to writing code for larger projects, so I 100% believe that you're correct.

Its more like a gut feeling that it doesn't belong there. For one, vorta could no longer be imported as a python module. Secondly `parse_args` would either be called twice or only in config which would be counter-intuitive which doesn't make the codebase more accessible for new contributors. Having argument handling and application setup in the main function, at the same place, seems like the proper and cleaner solution.

**Comment by ratchek** [comment]
Alrighty. Thanks for the explanation! I appreciate you taking the time.

**Comment by ratchek** [comment]
When going through the pull request checklist, it asks if I've modified the documentation appropriately. Where should I do that? And related issue, how would one modify the contributing guide to include the existence of this feature?

Also, the new folder I create that contains all the local changes is called 'dev' and is created in the root of the project. Does that seem appropriate or should I change the name and/or location to something else?

**Comment by real-yfprojects** [comment]
> And related issue, how would one modify the contributing guide to include the existence of this feature?

That isn't needed. But there is a repository for the `vorta.borgbase.com` website.

> Where should I do that?

Only if appropriate: docstrings and vorta website. Often this is not needed.





> Also, the new folder I create that contains all the local changes is called 'dev' and is created in the root of the project. Does that seem appropriate or should I change the name and/or location to something else?

How does it determine the root? I think the folder should start with a dot and should be named in such a way that makes clear that this is a config folder of vorta.



> 1. I need to run vorta from the terminal with and without the flag. How do I do that in pytest?

You can't at the moment. You could implement this (or skip writing tests) by moving the `main` function out of `__main__`. This allows you to call it from a test.

> I need to assert that it creates the appropriate folders if there are none. How do I do this without overriding folders that can potentially already exist?

Run in a temporary directory (see corresponding python module).

**Comment by ratchek** [comment]
DEV_MODE_DIR = Path(__file__).parent.parent.parent / 'dev'

> How does it determine the root? 
It looks at the __path__ variable and then traverses up the dir tree. This is an example:
`DEV_MODE_DIR = Path(__file__).parent.parent.parent / '.dev_config'`
Also, would `.dev_config` be an appropriate name for the directory?

> You can't at the moment. You could implement this (or skip writing tests) by moving the main function out of __main__. This allows you to call it from a test.
Would it be ok if I skipped writing these tests? I don't know how strict you guys are with your code coverage requirements.

**Comment by real-yfprojects** [comment]
> Would it be ok if I skipped writing these tests? I don't know how strict you guys are with your code coverage requirements.

We don't enforce them on ourselves. So I would be fine with skipping the tests for now. But maybe we should create an issue for adding such tests.

> t looks at the `__path__` variable and then traverses up the dir tree. This is an example:
> `DEV_MODE_DIR = Path(__file__).parent.parent.parent / '.dev_config'`

Do you want to hardcode the location? What about traversing up the directory until there is a `.git` folder? I think there should also be the option to specify a custom location through the command line.

**Comment by ratchek** [comment]
> We don't enforce them on ourselves. So I would be fine with skipping the tests for now. But maybe we should create an issue for adding such tests.

Ok, I'll do that.
 
> Do you want to hardcode the location? What about traversing up the directory until there is a .git folder?

I feel like that's a bit less readable because you have to loop over the directories AND you need a separate constant to keep the name of the actual directory somewhere, so it's easily changeable later. This way it's a one-liner. But I definitely rewrite it so it uses the `.git` approach if you think it's much better.

> I think there should also be the option to specify a custom location through the command line.

Do you think that's a feature that would be used a lot? If anything maybe we can open a new pull request with it and see if people want that? 

> Vorta could even look for a specific file/folder in the cwd, so that developer doesn't always have to pass the flag. It could use pyproject.toml like other dev tools.

Also, I don't think that the custom dev_folder location would synergize well with this feature and I think this is a much more useful feature to have.

**Comment by ratchek** [comment]
Ok, I see. So should both the location and name of the folder be configurable via command line flag or just the name?

**Comment by real-yfprojects** [comment]
> So should both the location and name of the folder be configurable via command line flag or just the name?

I suggest expecting the full path: `--dev ../somepath/config_folder`

**Comment by ratchek** [comment]
Should I restrict the path to be inside the project directory tree? And if not, how do I sanitize the input string to make sure it's an actual valid path? Or just not do that and throw exceptions if anything happens?

**Comment by real-yfprojects** [comment]
> Should I restrict the path to be inside the project directory tree?

No, I wouldn't recommend that.
