### ISSUE TITLE
When execution of a (create) job is terminated the logs do not contain `returncode=2`.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1183]
**Describe the bug**
When the job starts, an event log is created with `start_time = end_time = now` and `returncode=1`. 
If the computer is shut down for example the job won't be able to finish and its abortion can't be handled by the vorta process.
Still the logs will keep a returncode of `1`. This is a problem for the *create* command since the scheduler will think it was a successful backup.
Instead `returncode` should be set to `2` (=abnormal termination) and only updated to 0 or 1 (=no errors or minor permission errors) after the backup task is complete.

Furthermore, the scheduler should filter by `returncode` of the event and only consider events with 0 or 1 return codes.

I don't know whether this behaviour is a problem for other kinds of jobs as well. Additionally the title of this issue might not be the most fitting.

Related to #1130.

**Comment by real-yfprojects** [comment]
@m3nu Is this a thing for other *borg* commands/jobs as well?

**Comment by m3nu** [comment]
> the scheduler should filter by returncode of the event and only consider events with 0 or 1 return codes.

Agree. Did you check if this is the case now?

So your suggestion is to put -1 or some other error code in the logs when a task starts and then update it with the actual result later. So we know which job completed?

That should be fine and a good addition. It will be most useful for the scheduler, since we don't use events much in other places (but we should use them more probably)
