### ISSUE TITLE
display borg version also?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#120]
vorta already displays its own version.

it might be interesting to also display:
- borg version
- msgpack version
- python version

**Comment by m3nu** [comment]
In theory the `borg` binary could change while Vorta is running. Since the binary is being [search](https://github.com/borgbase/vorta/blob/master/src/vorta/borg/borg_thread.py#L119) before very run.

One solution would be to run an async borg command when the *Misc* tab is opened and populate the detailed version when it's ready. Is there a command to get all three versions? What's displayed as Python version when a fat binary is used?

**Comment by ThomasWaldmann** [comment]
True, but I think the borg changing case is a minor issue. Either the users themselves did an upgrade and are aware or it might be a minor upgrade installed automatically my the OS dist.

Hmm, iirc there is some open ticket on the borg issue tracker about some "borg system info" or so command, maybe we should check / enhance that first.

**Comment by m3nu** [comment]
Implemented in #247
