### ISSUE TITLE
ERROR - Connection closed by remote host. Is borg working on the server?

### ISSUE THREAD

**Issue by jchhenderson** [borgbase/vorta#1346]
**Describe the bug**

**To Reproduce**
1. Simply running a scheduled daily backup2. 

**Environment (please complete the following information):**
- OS: MacOS 12.4
- Vorta version: 0.8.6
- Installed from: ...not sure what this means

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
- There have been several failures in a row.
- Starting backup manually results in same error.
- Local backup (to NAS) is fine.

[vorta.log](https://github.com/borgbase/vorta/files/8823752/vorta.log)

**Comment by jchhenderson** [comment]
OK, now working after a couple of re-attempts.  Is there a sporadic issue?

**Comment by m3nu** [comment]
Hi, for BorgBase issues, you can just email support.

> Remote: kex_exchange_identification: Connection closed by remote host

This error could be caused by the data center's DDoS system. They sometimes randomly turn it on for an hour at the time and it will cause the first SSH connection to fail. All others succeed. Workaround is to make a connection to port 22 before the backup or enable [retries](https://docs.borgbase.com/faq/#enable-automatic-retries-in-borgmatic). Sadly we can't change this for now.

**Comment by jchhenderson** [comment]
> Hi, for BorgBase issues, you can just email support.

Thanks!

> Workaround is to make a connection to port 22 before the backup or enable [retries](https://docs.borgbase.com/faq/#enable-automatic-retries-in-borgmatic).

I'm here now, so quick question: Is _retries_ his possible in Vorta (I can't see an option for it)?

**Comment by m3nu** [comment]
No retries yet, because it’s not really an issue. Never once saw it myself.

**Comment by aeollos76** [comment]
> OK, now working after a couple of re-attempts. Is there a sporadic issue?

Hi please advise what was the work around as i am having the same issue.

thanks
