### ISSUE TITLE
dark mode doesn't activate on XFCE + Adwaita-dark

### ISSUE THREAD

**Issue by chaserene** [borgbase/vorta#1365]
**Describe the bug**
the interface remains in the default (light) mode under XFCE with the Adwaita-dark theme.

**To Reproduce**
1. install Debian 11 with XFCE
2. set theme to Adwaita-dark
3. install Vorta from the Debian stable apt repo
4. launch Vorta

**Environment (please complete the following information):**
- OS: Debian 11
- Vorta version: 0.7.5-1
- Installed from: Debian stable apt repo

**Comment by m3nu** [comment]
Will this also happen with the current version?

Dark mode is detected using color differences. Probably your issue comes from there https://github.com/borgbase/vorta/blob/add1ac7041eee2d5a26e77350eb9779357dcbd6a/src/vorta/utils.py#L323

**Comment by real-yfprojects** [comment]
> Dark mode is detected using color differences. Probably your issue comes from there
> 
> https://github.com/borgbase/vorta/blob/add1ac7041eee2d5a26e77350eb9779357dcbd6a/src/vorta/utils.py#L323

Vorta only adjust the icon's colour in dark mode itself. The GUI foreground and background colour is set by Qt that should detect the global desktop theme.

If this also occurs when installing vorta from source, it is an issue of Qt in combination with XFCE. You will find dozens of guides for integrating Qt in XFCE on the internet. I personally found Kvantum working nicely on gtk desktops.

Otherwise this is an issue of the Debian package.
