### ISSUE TITLE
Cannot add directory as Repository

### ISSUE THREAD

**Issue by JanSchnacki** [borgbase/vorta#14]
I guess this is not the most frequent setup, but I'm using a CIFS-mount from my NAS as a repository. Compared to getting borg installed on it, this is much easier.

Unfortunately, vorta currently only allows SSH-repositories. Is there any chance that you will support simple directories as repositories?

**Comment by m3nu** [comment]
I considered this, as I'm also backing up to some external drives.

Since there is almost not difference in the commands, I'll probably support it. But there needs to be a distinction between local and remote. E.g. the restricted Wifi option doesn't apply, but I may want to look for mounts.

Let's collect the required features here and then I'll add them.

**Comment by m3nu** [comment]
This also ties into #5. Since you likely have some remote and some local repos.

**Comment by JanSchnacki** [comment]
Yeah, checking for presence of the mountpoint **can** be beneficial. But... ;)

I'm using the "automount" parameter for this mountpoint, which causes it to be mounted on first access. So (for me) this would need to be an optional check.

**Comment by m3nu** [comment]
Added this feature. Seems to work fine, but needs some more testing before release.
