### ISSUE TITLE
FR: Show progress on consistency check

### ISSUE THREAD

**Issue by Justinzobel** [borgbase/vorta#1497]
#### The problem
Consistency checks can take a long time when the data set is quite large.

#### Requested Solution
Add a progress information and if possible an ETA

**Comment by irfanhakim-as** [comment]
This is absolutely crucial to me. I think how Vorta shows progress when backing up is fantastic and gives me a sense of security in knowing what it's doing and at what stage it is at in doing its task. Consistency checks at the moment is a completely stark contrast to that.

**Comment by m3nu** [comment]
Doesn't it show the progress per-archive already?

**Comment by irfanhakim-as** [comment]
> Doesn't it show the progress per-archive already?

In my case, it's the consistency check for repo that's running/stalling for over 4 hours (and ongoing) with no info in the UI or the logs. The UI just says "Starting consistency check... INFO: Starting repository check" while the last log in the UI was from the scheduled `create` command. I assume OP might mean the same too, since i saw u mention that archive consistency checks do have logs shown.

I believe the reason why this feature is not already available, is maybe because it's not possible? I've never used `borg` without Vorta so I don't actually know, but from this discussion #802 u mentioned that "there is no log output for the first repo check part", but only for the second archive check.

**Comment by m3nu** [comment]
Maybe if you set the debug output for Borg really high? If that doesn't help, we can't do much and this should be an issue with Borg itself.

**Comment by irfanhakim-as** [comment]
For one, i'm not sure if we could do so by, say, passing `--debug` to `borg check` in Vorta? all i see is the option to pass in such flags for `borg create` under the "Shell Commands" section.

Also, would that actually add progress information of `borg check` (repo/archive) to the UI like it does for `borg create` (which is my request). Or would that only, at least add such info to the "Log" section of the UI, under the "Schedule" tab?

Current `borg check`:

![Screenshot_20122022_010036](https://user-images.githubusercontent.com/69845406/208480875-835485ce-41bb-4df1-a9c9-020180aac63c.png)

Current `borg create` (desired outcome of `borg check`):

![Screenshot_19122022_205430](https://user-images.githubusercontent.com/69845406/208481022-8e517b8b-832b-4a33-91b4-5050ba0cba4c.png)

**Comment by real-yfprojects** [comment]
Borg will log `Starting consistancy check`. Then it takes time checking the repository as a whole. Only after that borg will log further status reports when checking the archives one after another.
```
INFO: Analysing archive ... 34/40
```
However when running with the `--progress` flag borg will show continuous progress information in both stages.

**Comment by endumiuz** [comment]
I fixed this locally yesterday. Making a PR when I get home.

**Comment by irfanhakim-as** [comment]
> I fixed this locally yesterday. Making a PR when I get home.

@endumiuz awesome!
