### ISSUE TITLE
Display mode of diff view should be remembered as setting when restarting Vorta

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1516]
I use the latest Flatpak version 0.8.9.

**Comment by real-yfprojects** [comment]
What is the reasoning of this request?

**Comment by sudwhiwdh** [comment]
> What is the reasoning of this request?

Because it is my preferred view and I don't want to select it every time. Is there any idea why the setting is not saved so far or is there something that speaks against it that I can't assess at this point?

**Comment by real-yfprojects** [comment]
> Is there any idea why the setting is not saved so far or is there something that speaks against it that I can't assess at this point?

There is nothing that speaks against it. However it is not implemented yet -> a new settings entry will have to be created for it.

**Comment by Saiesh-Agre** [comment]
I would like to solve this issue, can you help me get started?

**Comment by real-yfprojects** [comment]
> I would like to solve this issue, can you help me get started?

Have a look at existing settings:
https://github.com/borgbase/vorta/blob/78ec74a72cecc8198b2422470ac6c4587ee08fd6/src/vorta/store/settings.py#L78-L83

The display mode is used in the diff and extract dialogs:

https://github.com/borgbase/vorta/blob/78ec74a72cecc8198b2422470ac6c4587ee08fd6/src/vorta/views/diff_result.py#L56

https://github.com/borgbase/vorta/blob/78ec74a72cecc8198b2422470ac6c4587ee08fd6/src/vorta/views/extract_dialog.py#L42

**Comment by diivi** [comment]
@Saiesh-Agre are you still working on this issue? If not, I would like to get this assigned to me :)

**Comment by real-yfprojects** [comment]
> The easiest solution for me would be to add FlatList to Extract view too

do want to share the setting between the two views? 

I didn't add the flat mode on purpose but I dont remember why. I guess I didn't find it useful.

**Comment by diivi** [comment]
> do want to share the setting between the two views?

Yeah, I thought that might be more elegant, because earlier the `FileTreeModel` class was instantiated with `Tree` as the mode. But when I add this setting and follow these steps:
Change diff view to FlatList -> open extract dialog. 
I get a flatlist view and an empty combobox  (Because there is no option for it).
If I follow your approach though, (two different settings), I might have to change the implementation of `FileTreeModel` class, here are my current changes:
![image](https://user-images.githubusercontent.com/41837037/222275997-71481657-17ae-43b2-b5ce-92a38c726338.png)
Adding two settings might make this more complex because the same base class is being used. I'll have to tell where this class was called from (maybe by passing an extra parameter).
Let me know what you think, thanks!

**Comment by real-yfprojects** [comment]
I don't think the TreeModel should possess knowledge about the way settings are stored.

**Comment by sudwhiwdh** [comment]
Should these settings be part of a profile export?

**Comment by real-yfprojects** [comment]
No, I dont think so. This isn't a backup but a ui configuration.
