### ISSUE TITLE
Running tests on live borg binary

### ISSUE THREAD

**Issue by jetchirag** [borgbase/vorta#1711]
Details about the issue here: https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas#test-on-live-borg-binary

I'm planning how we can optimally go about it. Currently I've tested two methods

## 1. Using tox
we can test vorta in seperate virtual envs managed by tox simply by defining the versions in configuration file. Something like
```
[tox]
envlist = py38, borg2.0.0b5

[testenv]
deps =
    pytest
    -r requirements.d/dev.txt
commands = pytest {posargs}

[testenv:borg2.0.0b5]
deps = pytest
       borgbackup==2.0.0b5
```

Then we can replace the mock functions in the tests to actually run the code which won't need any non-test code change.

Small note: I experienced incompatibility issue with this approach on M1
```
...
File "/Users/chirag/Projects/vorta/vorta/.tox/borg1.2.4/lib/python3.9/site-packages/borg/archiver.py", line 38, in <module>
    from .algorithms.checksums import crc32
ImportError: dlopen(/Users/chirag/Projects/vorta/vorta/.tox/borg1.2.4/lib/python3.9/site-packages/borg/algorithms/checksums.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_XXH64'
```

## 2. Custom config file and parameterizing pytests
A config file to manually add paths for each version to test:
```
versions:
  - version: v124
    path: /path/borg1
  - version: v20
    path: /path/borg2
```
then parameterizing all tests using borg command
conftest.py:
```
import configparser


config = configparser.ConfigParser()
config.read('config.ini')
borg_versions = [v for v in config['versions'].values()]


def pytest_addoption(parser):
    parser.addoption(
        "--borgversion",
        action="append",
        default=[],
        help="test only for specified borg version",
    )


def pytest_generate_tests(metafunc):
    borg_version = metafunc.config.getoption("borgversion")

    if "borg_path" in metafunc.fixturenames:
        if borg_version:
            metafunc.parametrize("borg_path", borg_version)
        else:    
            metafunc.parametrize("borg_path", borg_versions)
```

Which one would you prefer in your flow? Second option seems more convenient to me but not standard.

I'm new to tox and testing in general so any pointers is appreciated as well.

**Comment by real-yfprojects** [comment]
Tox has the disadvantage that you have to specify every single borg version manually !multiple! times. You have to specify the version once in the env name and once as the actual dependency version. On the other hand tox is maintained tool with plenty of features. So instead of implementing our own version of a testing framework we could use tox to reduce the work needed now and in the future.

I found [nox](https://github.com/wntrblm/nox) which is like tox but using a python script as configuration file. It solves the issue I described above and supports easy to use [parametrization](https://nox.thea.codes/en/stable/tutorial.html#parametrization) out of the box.


> Small note: I experienced incompatibility issue with this approach on M1

Is this a tox issue or a general issue with building borg from source on M1?

> Then we can replace the mock functions in the tests to actually run the code which won't need any non-test code change.

Either way the tests will not work out of the box since they use output from repos with actual contents.

> A config file to manually add paths for each version to test:
> 
> ```
> versions:
>   - version: v124
>     path: /path/borg1
>   - version: v20
>     path: /path/borg2
> ```

This will require the user to install every borg version tested manually, determining their installation location and configuring set location in the script. Furthermore each dev has to keep their own testing config. However the versions tested should be configured in a file that is included in the repo so that all devs share the same test setup.

**Comment by jetchirag** [comment]
> Is this a tox issue or a general issue with building borg from source on M1?

I assumed it was virtualenv issue but I'm getting it on global install as well. Perhaps an issue with my setup but I didn't find a solution yet.

Switched to a Linux VM for this task and Nox seems great.

```
import nox

@nox.session
@nox.parametrize("borgbackup", ["2.0.0b5", "2.0.0b4"])
def test(session, borgbackup):
    session.install(f"borgbackup=={borgbackup}")
    session.run("borg", "--version", external=True)
```
<details>
  <summary>Output</summary>

```
└─$ nox
nox > Running session test(borgbackup='2.0.0b5')
nox > Creating virtual environment (virtualenv) using python3.11 in .nox/test-borgbackup-2-0-0b5
nox > python -m pip install borgbackup==2.0.0b5
nox > borg --version
borg 2.0.0b5
nox > Session test(borgbackup='2.0.0b5') was successful.
nox > Running session test(borgbackup='2.0.0b4')
nox > Creating virtual environment (virtualenv) using python3.11 in .nox/test-borgbackup-2-0-0b4
nox > python -m pip install borgbackup==2.0.0b4
nox > borg --version
borg 2.0.0b4
nox > Session test(borgbackup='2.0.0b4') was successful.
nox > Ran multiple sessions:
nox > * test(borgbackup='2.0.0b5'): success
nox > * test(borgbackup='2.0.0b4'): success
```

</details>

I'll try writing a live test with it tomorrow.

**Comment by jetchirag** [comment]
What versions we need to be testing? Stable v1.2.4, to which release and development branch 2.0.0b5?

**Comment by m3nu** [comment]
Yes, the current 1.2.x branch and future 2.x branch. Maybe also the older 1.1.x branch.

**Comment by real-yfprojects** [comment]
I would propose that we test all officially supported versions. Which versions are officially supported?

**Comment by jetchirag** [comment]
According to https://www.borgbackup.org/releases/, 1.1 and onwards are supported.

**Comment by real-yfprojects** [comment]
> According to https://www.borgbackup.org/releases/, 1.1 and onwards are supported.

Oh, this also relevant information although I wanted to ask which versions Vorta officially supports.

**Comment by jetchirag** [comment]
test_archives.py and test_borg.py are (almost) completed. I can currently see following test pending:

test_repo.py::test_create

Are there any other I missed or new ones we can test?

**Comment by real-yfprojects** [comment]
> Are there any other I missed or new ones we can test?

What about `test_lock.py`? Also you could add tests for `borg init` and `borg info` as well as running `borg diff` and parsing its output.

**Comment by jetchirag** [comment]
@real-yfprojects Can you give me clue regarding `borg diff`? Unit tests already seem to check if lines are parsed correctly so should I just compare the output of borg diff of each archive with expected value? Though that would be more of borg testing than vorta.

**Comment by real-yfprojects** [comment]
> Unit tests already seem to check if lines are parsed correctly so should I just compare the output of borg diff of each archive with expected value? Though that would be more of borg testing than vorta.

IMO we don't need any integration tests for the json diffs. However the human-readable output for the early borg version isn't documented. Therefore it would be useful to test whether vorta is able to parse their output. You could either check whether the borg output matches the mock output used in the unit tests or pass the borg output to the parser and validate the parsed data which would be more. The latter would be more robust to changes in the human readable format. However that format shouldn't change since it is only taken from old versions that do not receive new patches.

**Comment by real-yfprojects** [comment]
Best would be having a matrix of python versions (and maybe even borg versions) creating a job each that only runs nox for that python version (or combination of versions). Is that possible with nox?

**Comment by jetchirag** [comment]
That sounds good. Each job would have maximum of 4 runs under nox.

> Is that possible with nox?
We can remove python version parameterization from nox (and use system installed) but will need to add condition somehow for min python version requirement for each borg version.

**Comment by jetchirag** [comment]
@real-yfprojects 

> Job matrix - A job matrix can generate a maximum of 256 jobs per workflow run. This limit applies to both GitHub-hosted and self-hosted runners.

If we directly use matrix to generate jobs for supported borg version, we wouldn't need to use nox parameterization. It should be faster too since 20 job can run concurrently according to https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

But will need to check how we can exclude combination conditionally based on version requirements.
