### ISSUE TITLE
FR: compacting schedule like we do for pruning

### ISSUE THREAD

**Issue by marco44** [borgbase/vorta#1718]
#### The problem

I just recently upgraded to borg 1.2. The repo started growing very fast, and I learn that now we need to run compact at regular intervals to reclaim space. The compact button allowed me to recover the lost space for my repo. But I feel it should be run regularly, like we do for pruning or validation

#### Requested Solution

Having the possibility to compact after each backup or at regular interval.

#### Additional context

I saw some discussions about this in other issues about compact, but nothing clearly about this. Maybe I missed something?

**Comment by m3nu** [comment]
Would fit nicely under *Schedule*. Similar to *Validation*. *Ever X weeks* etc.

![Screenshot 2023-05-22 at 15 13 07](https://github.com/borgbase/vorta/assets/3916435/62c0bd0d-a268-4f35-8bdc-9f94606fd2e4)

**Comment by marco44** [comment]
Yeah, but which one would be better ? Like autopruning, or like validation ? I think both have their merits. I suppose borg developers had a reason for not compacting on each run...

**Comment by real-yfprojects** [comment]
> I suppose borg developers had a reason for not compacting on each run...

I'd do it like validation.

**Comment by masterjuggler** [comment]
Is this something that is in line to be added at some point? Right now I have to either set a cron job or add it as a post-backup shell command, which works but isn't obvious for people setting up a new repo.

**Comment by m3nu** [comment]
Could be added and grouped with pruning. Like *Run post-backup tasks* > *Prune*, *Compact*

**Comment by masterjuggler** [comment]
If it's not a major effort to add, I think it would be worthwhile because it's something that's very easy for most people to not realize is a necessary manual step, which results in a very bloated repo.

**Comment by Gerben321** [comment]
Would indeed be a nice feature. I noticed some unexplainable large files on my Unraid server and traced it back to my Vorta destination folder on another server. My supposedly ~5GB backup has become 262GB. I am now compacting it. Would be great to have the option to do it automatically once in a while or after each prune or something. Shouldn't be that difficult.

**Comment by ThomasWaldmann** [comment]
I just put this into next milestone, this should get a high priority.

If implementing something advanced takes longer, something simple should be done ASAP so that "borg compact" is invoked. Not invoking it at all without user interaction is no good idea, backup space usage is exploding for some people until they notice they have to click on "compact" manually. If people did not set up repository quota or reserved space somehow they might even run completely out of free fs space, which is a known very bad situation with borg.

So, a quick fix would be vorta just doing a borg compact implicitly after each borg prune, no matter whether it was invoked manually or automatically.

**Comment by shivansh02** [comment]
Hi I'd like to work on this. Should I go for the quick fix first, by running `borg compact `after each prune, or start working on the scheduling?
