### ISSUE TITLE
Please label pre-releases v0.9.0-alpha or -beta for instance so https://release-monitoring.org can detect them

### ISSUE THREAD

**Issue by Justinzobel** [borgbase/vorta#1741]
Please label pre-releases v0.9.0-alpha or -beta for instance so https://release-monitoring.org can detect them

**Comment by real-yfprojects** [comment]
:+1: Makes sense!

**Comment by Justinzobel** [comment]
That would work too, as long as the actual version has a suffix that release-monitoring can be told about. Right now it's not in the version it's in some metadata in GitHub.

**Comment by m3nu** [comment]
Yes, we can put e.g. `0.9beta1`.

Could be good to have a few betas to encourage testing. Since there will be more changes while our Google Summer of Code guys work on Vorta.

**Comment by sten0** [comment]
Please note that because the v0.9.0 tag was already used, the "0.9.0" (including "0.9") logical version has already been used in some version tracking systems (ie Debian's, https://repology.org/project/vorta/versions, etc).  This means that the eventual actual "0.9.0" release will need to use a post-release convention.  I guess there's a PEP 440 + PyPI technicality here, because 0.9.0 wasn't released on PyPI...  Nonetheless, the v0.9.0 tag has been used.  That ship has sailed.

Here's a method you can use to test version sorting when considering version numbers: https://www.gnu.org/software/coreutils/manual/html_node/Comparing-two-strings-using-Debian_0027s-algorithm.html

**Comment by sten0** [comment]
P.S. Sorry, I forgot to mention one Debian-specific thing.  Normally we use the tilde convention for prereleases, ie: 0.9.0~alpha always sorts before 0.9.0; however, 0.9.0 sorts before 0.9.0alpha.

**Comment by sten0** [comment]
Also, Release Monitoring is correctly detecting the 0.9.0 github tag.  https://release-monitoring.org/projects/search/?pattern=vorta

**Comment by real-yfprojects** [comment]
I guess we have decided to conform to PEP 440 in the future. Can this issue be closed then?

**Comment by m3nu** [comment]
Yes, can be closed. I've added this decision also to the contributor docs.

https://github.com/borgbase/vorta.borgbase.com/commit/55709c750f2e6749452f0e46f07908820ed5cd29
