### ISSUE TITLE
Notification for disallowed backups from tray icon when 'Current Wifi is not allowed' [Mac OS]

### ISSUE THREAD

**Issue by adamluk** [borgbase/vorta#19]
Perhaps it would be good to notify in the event of failed manual backup, due to being connected to a Wifi network that is not selected as allowed. Only one notification seems to trigger, all subsequent backups fail silently and any attempts to run a manual backup also fail silently. Food for thought :)

**Comment by m3nu** [comment]
This already exists and works. Any error will be shown as notification if something fails for a background job. Including disallowed Wifis.

BUT you will only see the notification when running Vorta from the app bundle (`Vorta.app`). You won't get it when running it as Python script due to macOS limitations.

<img width="496" alt="screenshot 2018-11-20 at 08 58 09" src="https://user-images.githubusercontent.com/3916435/48744537-97c61b80-eca2-11e8-96ac-23240ea852c8.png">

**Comment by adamluk** [comment]
This issue is still persisting for me. Attempts to manually run a backup from a disallowed Wifi network do not complete, this is correct - however no notification is displayed and no error shows in the log. I do receive notifications for failed scheduled backups though.

I've emailed you a screencast for clarification.

**Comment by m3nu** [comment]
That sounds correct. There are **no notifications** for user-initiated foreground tasks or backups. Since the user sees the error anyways.

There are only notifications for background tasks since the user can't see those.

Would you prefer having notifications all the time? Personally I would find it too much.

**Comment by adamluk** [comment]
Yes that makes sense. Happy for you to leave this issue closed.

**Comment by m3nu** [comment]
Thanks for the input anyways. It's always good to have one's assumptions challenged. For most other things you suggested, you were totally right. Like the wifi stuff. It started to bug me as well.
