### ISSUE TITLE
Minute extra added to the cron job?

### ISSUE THREAD

**Issue by M-Gonzalo** [borgbase/vorta#1935]
### Description

I don't know how to describe this except by showing some screenshots. I have Vorta set up to perform a backup every hour, and it's making them every ~61 minutes
![Screenshot_20240212_200935](https://github.com/borgbase/vorta/assets/23223606/30fd79a4-b414-468f-9444-1d2de00f3aa8)
![Screenshot_20240212_200913](https://github.com/borgbase/vorta/assets/23223606/9304bc31-f370-41d7-aca5-dc2dc708470b)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux x86-64 (Arch derivative, up-to-date), KDE

### Version of Vorta

0.9.1 

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.4

**Comment by jetchirag** [comment]
This seems to be the intended behaviour. Vorta schedules next backup after 1 hour since 'finish' time of last backup. It's not run every 1 hour but 1 hour from last run.

So depending on time taken by last run, scheduled time will also change. 

https://github.com/borgbase/vorta/blob/master/src/vorta/scheduler.py#L271-L275

**Comment by m3nu** [comment]
We use QtTimer internally, which has some limitations. There is also the issue of having backup tasks that run for a long time. So it made sense to schedule the next job some amount after the previous one.
