### ISSUE TITLE
Warnings when running Vorta

### ISSUE THREAD

**Issue by HLK6** [borgbase/vorta#1978]
### Description

2024-03-29 14:00:57,116 - vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events

Each time I run Vorta on my POP_OS laptop I receive the above warning.  When I run it on my POP_OS I do not receive the warning.  Ostensibly, both machines run the same.  This started occurring in December 2023.  Otherwise the backup appears to be functioning properly.

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

POP_OS

### Version of Vorta

0.9.1

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.4

### Logs

```pytb
/home/herb/.var/app/com.borgbase.Vorta/.local/state/Vorta/log/vorta.log
```

**Comment by SAMAD101** [comment]
I think the problem lies in that you are using the Flatpak version of Vorta. Flatpak apps are usually unable to connect with the system as well because of sandboxing. I'd suggest you download Vorta from pip or apt.

Alternatively, you can try disabling sandboxing in flatpaks. But this will take more efforts. https://www.reddit.com/r/flatpak/comments/thu9g8/what_does_sandboxing_in_flatpak_even_mean/
