### ISSUE TITLE
Wrong language shown in gui

### ISSUE THREAD

**Issue by macau23** [borgbase/vorta#2112]
### Description

My locale is set to en_AT, but the GUI is showing mixed English and German.

It should be showing English.

Issues #623 and #919 are the same problem, but the suggestion there was to amend locale (my locale is fine!)

### Reproduction

- [X] I tried to reproduce the issue.
- [x] I was able to reproduce the issue.

### OS

MacOS 15.1

### Version of Vorta

v0.10.0-beta1

### What did you install Vorta with?

Binary

**Comment by rriley** [comment]
I'm having a similar issue.  After a recent update, Vorta on OSX is now entirely in Arabic despite my primary language being English.

Here is a screenshot:
<img width="700" alt="image" src="https://github.com/user-attachments/assets/4fc094e3-211c-4f48-9800-e7bc56096d22">

Here is the relevant log entry:
```
2024-11-14 10:48:58,205 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-QA', 'en-Latn-QA', 'ar-QA', 'ar-Arab-QA'].
```

**Comment by m3nu** [comment]
Loading translations happens in Qt, not Vorta. But you can override it by setting the `LANG` env var. E.g. `LANG=en`.

Relevant code and docs:
- https://github.com/borgbase/vorta/blob/master/src/vorta/i18n/__init__.py#L59
- https://doc.qt.io/qt-6/qlocale.html#system

**Comment by themightyoarfish** [comment]
I have this same problem suddenly. How can I set the LANG env var for vorta?

**Comment by themightyoarfish** [comment]
Yeah, but how can I do this for normal operation? I don't think most users will start the app from the command line?

In my shell, `LANG` is set to `en_US.UTF-8`, but this does not affect Vorta, so I'm curious where exactly lies the reason for it using German locale.

**Comment by NaoPross** [comment]
Same issue, I had set up my Mac with English (UK) and added the other languages later but since the last update it decided to always pick German.

![Screenshot 2024-11-20 at 23 11 06](https://github.com/user-attachments/assets/7764fdbf-3dba-4c6a-9000-f76bfe69ade2)

On the command line I get
```
$ locale
LANG=""
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
Vorta Logs
```
vorta.log:2024-11-20 23:08:47,258 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-CH', 'en-Latn-CH', 'it-CH', 'it-Latn-CH', 'de-CH', 'de-Latn-CH', 'fr-CH', 'fr-Latn-CH', 'ja-CH', 'ja-Jpan-CH', 'ru-CH', 'ru-Cyrl-CH'].
```
Looking at what `QLocale` does it seems to be correctly picking English as the first language, though MacOS did something weird and changed my `en-GB` (and everything else) to `en-CH`
```python3
(venv) npross@titan /tmp/test $ ipython3
Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.29.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: from PyQt6.QtCore import QLocale

[ins] In [2]: QLocale().uiLanguages()
Out[2]: 
['en-CH',
 'en-Latn-CH',
 'it-CH',
 'it-Latn-CH',
 'de-CH',
 'de-Latn-CH',
 'fr-CH',
 'fr-Latn-CH',
 'ja-CH',
 'ja-Jpan-CH',
 'ru-CH',
 'ru-Cyrl-CH']
```
If you sort this list `de-CH` comes first and that is my best guess for why German (or _Arabic_ but not _French_). However, your code does not seem to be doing any sorting so ... `¯\_(ツ)_/¯`

Maybe doing the following using 
https://doc.qt.io/qt-6/qtranslator.html#load
instead of
https://doc.qt.io/qt-6/qtranslator.html#load-1
could be a temporary fix
```python3
    ui_langs = locale.uiLanguages()
    succeeded = translator.load(ui_langs[0], 'vorta', prefix='.', directory=qm_path)
```

**Comment by m3nu** [comment]
Good observation on the sorting and testing. Made a PR and test build since the issue only seems to happen in app bundles and not from Python directly. Let me know if this works as expected for everyone:

https://files.pf7.net/vorta/Vorta-issue_2112-arm.dmg

**Comment by NaoPross** [comment]
Seems to work 👍
