### ISSUE TITLE
Backup fails when empty "exclude if present" is added to the list

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#2135]
### Description

Not sure how it got there, but I just had an empty item in the "Exclude if present" list. I realized this as my backup finished after a few seconds without error. 

The log shows:
`Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe create --list --progress --info --log-json --json --filter=AM -C lz4 --patterns-from=/Users/mo/Backup/excludes/borg_excl_patterns.lst --exclude-if-present .nobackup --exclude-if-present  ssh://PATH-TO-ARCHIVE /BACKUP/PATH`

The issue seems to be that an empty "--exclude-if-present" is passed to borg and probably the rest of the command gets broken.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macOS 15.1 (24B83)

### Version of Vorta

0.10.1

### What did you install Vorta with?

Binary

### Version of Borg

1.4.0

### Logs

```pytb
See above
```

**Comment by m3nu** [comment]
What do you see in your _Exclude if Present_ dialog? Just checked the code and not sure how this could be empty. Of course we can add another check anyways.

**Comment by m3nu** [comment]
Can you check if

- The small change in #2136 fixes it?
- What's the content of `patterns` when the error happens in the same file? https://github.com/borgbase/vorta/pull/2136/files#diff-2559f308260b3597027f7b0650bc98f2783fbb1ed513a244a3ccb4756256d11cR173

**Comment by goebbe** [comment]
@deermo Did you define the "exclude if present" using Vortas "Manage Exclude Items"?
   Source>Mangage Exluded Items>Exclude If Present
The only way I could get this behaviour, using Vorta, is by at least putting one **space** " ", when adding a new "exclude if present" pattern. Without whitespace, no empty "exclude if present" pattern seems to be created anyway.
@m3nu I cannot test, right now - but the proposed change should indeed fix the issue, since, with the fix, the "exclude-if-present" is not created if the pattern contains only whitespace.

Sidenote: It is also possible to create custom exclude patterns with only whitespace " " in the "_Custom_" tab - but I guess in this case an empty (only whitespace) line in the --exclude-from file does not have unintended side effects.
