### ISSUE TITLE
Offer alternative scheduling options (e.g. crontab/systemd timer)

### ISSUE THREAD

**Issue by RlndVt** [borgbase/vorta#294]
**Is your feature request related to a problem? Please describe.**
If I'm not mistaken, Vorta's scheduler only works when Vorta is running in the background, if the background process crashes or is closed for what ever reason no new backups will be made. 

**Describe the solution you'd like**
Provide alternative scheduling options, for instance crontab. 

**Comparing with 'the competition'**
As an example, how 'backintime' schedules backups is very resilient and flexible:
https://backintime.readthedocs.io/en/latest/settings.html#schedule

Can't remember/find how 'timeshift' implements a scheduler but it also seems to be based on crontab.

**Related issues**
To be able to run from crontab a command must exist to start a backup job. #293 

Alternative scheduling solutions will allow starting at next opportunity #263 or on boot #112.

**Comment by m3nu** [comment]
Possible, but this would be very error-prone because Vorta doesn't know which scheduler is available on the current system. So it would need to detect that somehow. If we let the user choose, he needs to know about schedulers, which requires more expertise. What if the scheduler changes due to an update? Who will keep track of all the different schedulers on different systems?

Integrating such cross-platform features is very hard to do right. I saw it when adding the Keychain feature for macOS and Linux desktops. Autostart was the same. For our built-in scheduler we don't need to deal with that.

**Comment by Hofer-Julian** [comment]
Plus, it probably wouldn't work for the flatpak version.
