### ISSUE TITLE
Optimize Vorta refresh behavior 

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#366]
Currently Vorta refreshes after every profile change. This seems to have downsides.

Proposed new behavior:
- Refresh after the diff button is pressed
- Open error dialog after mounting, deletion,... of archive was attempted that does not exist anymore and advise to refresh the repository.

**Comment by hutson** [comment]
I do not know if it would go here, but after one of my backups failed, I needed to manually run `Refresh` to know that a checkpoint archive had been created - https://github.com/borgbase/vorta/issues/532#issuecomment-652166073

Because that was not automatic, I had no feedback that state on the remote repository had changed and no indication that my backup attempt had partially succeeded. At least no feedback until I manually ran a refresh.

**Comment by samuel-w** [comment]
I assume refresh means refreshing archives.
Does this behaviour exist anymore? Changing profiles doesn't refresh any archives for me.

**Comment by Hofer-Julian** [comment]
This behavior has indeed been removed by @m3nu's request

**Comment by samuel-w** [comment]
OK then, closing.

**Comment by Hofer-Julian** [comment]
Sure, if you want. The proposed new behavior hasn't been implemented though as far as I know 😊

**Comment by hutson** [comment]
While the functionality was removed, it appears that we could still benefit from more automated refreshes, just with a little more care as to when those refrshes happen - https://github.com/borgbase/vorta/pull/376#pullrequestreview-306321951

---
Sincerely,
Hutson Keith Betts
https://hyper-expanse.net/hutson
Encryption Key ID: 0x613EF24A9954F2FE
