### ISSUE TITLE
Do manual break-lock from UI

### ISSUE THREAD

**Issue by FlorianLudwig** [borgbase/vorta#374]
**Is your feature request related to a problem? Please describe.**
Vorta is unusable when the repo is locked.  Need to setup cli to use `break-lock`.

**Describe the solution you'd like**
When the repo is locked vorta should provide an option to run `break-lock`

**Comment by m3nu** [comment]
Agree that we should handle that. First Vorta would need to be smarter about error messages. Currently we only run the command and pass the log output to the UI.

**Comment by kevdogg** [comment]
Question about this problem -- Been running borg for years and recently found vorta.  Good lucking product.  To address the lock problem I used to put this line within my scripts:

```
borg break-lock $REPOSITORY

borg create $OPTIONS $REPOSITORY::`hostname`-`date +%Y-%m-%d--%H:%M:%S` \
```
I tried putting the borg break-lock command in the section labeled pre-backup but I don't think borg break-lock returns a code zero when an error does not occur.  Any other workaround -- possibly nesting this within a script that would return this value?

**Comment by m3nu** [comment]
Problem with *always* breaking the lock: What if there is really another process accessing the repo?

**Comment by kevdogg** [comment]
@m3nu 
I understand your concern since my solution doesn't scale very well for large deployments where multiple clients may be involved.  For my really small setup -- one computer->one archive-->one FreeNAS installation with script run by cron daily this is a workable solution.  I'm not sure how well borg would scale since when I made my small script several years ago, I was frequently getting lock file errors, possibly once a week.  I have no idea if with further iterations with borg if this problem has been mitigated since I've run borg (currently 1.1.10) with the break-lock option for the last several years without a problem.

**Comment by ThomasWaldmann** [comment]
You could run into an break-lock issue even with your simple setup:

Just imagine you start a manual backup using borg just short before your cron starts the script (for whatever reason). The lock will be held by your manual backup borg process.

Then your script starts while the manual backup is still running, breaks the (valid und required) lock and also does a backup.

This is the kind of problematic concurrent repo write access that normally gets avoided by the lock.

So, I'ld suggest not automatically breaking the lock in a script.

We improved locking behaviour over the last 1,2 years:
- for some situations, borg will automatically remove stale locks (if it can tell for sure the lock is really stale)
- exception handling was improved, so in crash/error situations stale locks should happen less often than in the early borg days

**Comment by m3nu** [comment]
We shouldn't break the lock automatically, but a break-lock button somewhere in the UI could be useful. Else I need to collect the repo URL and password first and then do it from the CLI.

**Comment by goebbe** [comment]
Perhaps it would be sensible to inform the user in Vorta about the reasons the repo might be locked. Something like: 

"It is only save to use "break-lock" if you are sure that no (other) instance of borg is currently writing to the repository"
Perhaps followed by a "Are you sure you want to break-lock?  (Y)es/(N)o"

And for the documentation of Vorta: 
While running a backup, the concerned repository is locked and no other backup can write to the repo at the same time. If this is the case, locking the repo is valid and required. Do not use "break-lock" in this case, but wait until the backup is finished.
If you are sure, that there is no backup running or the backup is stalled you might use the "break-lock" option in Vorta in order to manually remove the lock from the repository.

**Comment by mauromol** [comment]
Today it happened to me: the Vorta tray icon advised me that there was an error. First it was not that easy to find the logs, then I saw the tiny "Log" anchor in the bottom right corner of the "Various" tab of Vorta UI. From there, I had to figure out what is the right log file to look at, then I saw that the error was related to a lock problem. I then found out https://github.com/borgbackup/borg/issues/3191 and could figure out how to break the lock by using the command line.
I think Vorta should definitely provide a way to do this from the UI and possibly alert the user when the backup fails because of this specific error.

I now see there's also the Log subtab under the Scheduling tab, listing all the borg commands being fired by Vorta with the corresponding command, repository and error code, but I can't find a way to "zoom in" to see the corresponding log output (neither double click nor right click works), am I missing something?
