### ISSUE TITLE
Vorta - Borg binary not found

### ISSUE THREAD

**Issue by kevdogg** [borgbase/vorta#406]
**Describe the bug**
Borg binary not foind

**To Reproduce**
1. Program attempts to run on a schedule.  It's been working for many many months.  Now all of a sudden it states the borg binary can not be found.  This may have occurred after an update.  I'm not sure.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
Log file:
2020-02-21 06:42:00,089 - vorta.scheduler - ERROR - Borg binary was not found.
2020-02-21 06:42:00,090 - vorta.notifications - DEBUG - notification not suppressed
2020-02-21 06:42:00,093 - apscheduler.executors.default - INFO - Job "VortaScheduler.create_backup (trigger: cron[hour='*/6', minute='42'], next run at: 2020-02-21 12:42:00 CST)" executed successfully

Borg is installed within the system: (Installed via brew)
```
# which borg                                              
/usr/local/bin//borg
```

I'm not sure if borg is looking somewhere else for the binary such as within a venv.  It's clearly in the system.  If I run borg by itself on the command line at my user shell.

```
# borg -V                                                  
borg 1.1.10
```

Does borg have a separate PATH or env variable where it is looking?

I'm aware this issue has been reported before. Sorry

**Comment by m3nu** [comment]
Where did the extra slash in your path come from? `/usr/local/bin//borg`

Borg on the latest macOS installed as fat binary is problem due to Apple's new validation policy. I still need to dig into the issue in full.

**Comment by mplorentz** [comment]
This is happening to me as well, and I do not have an extra slash in my borg path. Happy to help with debugging if I can.

**Comment by m3nu** [comment]
Hey @kevdogg and @mplorentz, I did some work on the macOS release. The latest test release is now notarized and has a few default paths set, so Vorta should always find a Borg binary. It also includes a Borg binary as fallback, when using the macOS package.

Would be great if someone could test it: https://files.qmax.us/vorta/Vorta-0.6-24-testing.dmg

I also want to mention that there is a slight delay, when using the Borg single fat binary release (also installed by Homebrew) because macOS will validate every library online after it's unpacked. **Every time** you start the app. That's why it's better to install Borg via Pip instead, since the libs remain in the same place and are only checked one time.

**Comment by m3nu** [comment]
Another test release. This one comes with signed Borg, so macOS won't check anything and there is no delay in starting or running it.

https://files.qmax.us/vorta/Vorta-0.6.24-testing-signed-borg.dmg

**Comment by kevdogg** [comment]
Does this sit in a git repository anywhere?

**Comment by m3nu** [comment]
> Does this sit in a git repository anywhere?

It does.

- Pull request: https://github.com/borgbase/vorta/pull/407
- Feature branch: https://github.com/m3nu/vorta/tree/issue/406/macos-packaging

**Comment by mplorentz** [comment]
I have been using the build you linked for a few days with no issues. Thanks!

**Comment by m3nu** [comment]
Good to know, @mplorentz and thanks for testing!

I already did an [official release](https://github.com/borgbase/vorta/releases) and you should get automatic updates from here.
