### ISSUE TITLE
borg mount fails due to macOS notarization

### ISSUE THREAD

**Issue by robertlemke** [borgbase/vorta#420]
**Describe the bug**
Trying to mount an archive using Vorta on MacOS fails because Vorta can't load `libosxfuse.2.dylib`. FUSE for Mac is installed (and I also tried installing it again). I suspect that this error has something to do with the notarized released.

**To Reproduce**
1. Use Vorta v0.6.24 and FUSE for Mac 3.10.4
2. In Vorta go to "Archives"
3. Click on an archive and click on "mount"
4. An error is displayed (see below)

**Desktop:**
 - OS: MacOS 10.15.3

**Additional context**
```
2020-03-22 12:39:49,176 - vorta.borg.borg_thread - ERROR - borg mount not available: loading FUSE support failed [ImportError: dlopen(/Applications/Vorta.app/Contents/Resources/borg-dir/llfuse.cpython-37m-darwin.so, 2): Library not loaded: @loader_path/libosxfuse.2.dylib
  Referenced from: /Applications/Vorta.app/Contents/Resources/borg-dir/llfuse.cpython-37m-darwin.so
  Reason: no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs]
```

**Comment by deermo** [comment]
Identical problem with identical error message here.

**Comment by m3nu** [comment]
The error you are seeing is due to the notarization that is now mandated in macOS. It seems to impose some restrictions on linking libraries. I'll make sure this is done properly for the next release.

Thanks for reporting @deermo  and @robertlemke !

**Comment by ThomasWaldmann** [comment]
@m3nu when did this notarization craze on macOS start exactly? Just asking for my macOS test environment. :-)

**Comment by m3nu** [comment]
> @m3nu when did this notarization craze on macOS start exactly? Just asking for my macOS test environment. :-)

I was added in 10.15/Catalina, but they are more strictly [enforcing](https://developer.apple.com/news/?id=12232019a) it since Feb 2020.

The fat Borg bin doesn't work too well since then. Since it's unpacked and scanned every time there is a) a big warning or error when first opening it b) 20 seconds delay when starting it. Every time.

The workaround is to use Pyinstaller "one folder" mode instead of "one file" mode. That's what I did for Vorta. It ships with a notraized copy of Borg in "one folder" mode. So all the libs stay in the same place and macOS only verifies the notarization of the whole app. I mentioned this in a Borg Github issue, I think.

Currently I don't see a solution for Borg standalone, except using a different packager. The way Pyinstaller does it isn't compatible any more. For homebrew, we could probably ship a "one folder" version.

**Comment by m3nu** [comment]
This is tricky because the error happens in Borg, not Vorta. Borg excludes the FUSE libs to avoid version mismatches. So I'm not sure I should be smarter than add FUSE back in.

You can still try this package. It includes a few more libs and FUSE worked for me. You should still install FUSE first as well. We can't fully include it.

https://files.qmax.us/Vorta-test-2020-05-28b.dmg

See also #452

**Comment by m3nu** [comment]
Already got a chance to test this, @robertlemke ?

**Comment by robertlemke** [comment]
@m3nu thanks, I can confirm that mounting the archive in Catalina does work with the version you provided.

At first I thought it doesn't, but it just took quite a while until the volume was mounted.

**Comment by m3nu** [comment]
Yes, it can take a bit, depending on the size of the archive.

**Comment by uglygus** [comment]
I had the same issue as well on Catalina 10.15.5 and the new build above, [https://files.qmax.us/Vorta-test-2020-05-28b.dmg](https://files.qmax.us/Vorta-test-2020-05-28b.dmg), fixed the issue for me as well. Thanks

**Comment by Lazza** [comment]
The error is still present on Vorta 0.7.1...

**Comment by pin00b** [comment]
sorry for obviously duplicating, same error in my case, see #735
any help for resolving greatly appreciated, thanks!

**Comment by arnonel** [comment]
same for me
