### ISSUE TITLE
Deduplicated and Compressed sizes in the UI is wrong

### ISSUE THREAD

**Issue by caioau** [borgbase/vorta#472]
**Describe the bug**

The Deduplicated and Compressed sizes in the UI is wrong.

**To Reproduce**
Open Vorta

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 , vorta 0.6.24 , borg 1.1.11

** Screenshot **

![image](https://user-images.githubusercontent.com/18381590/83025462-8344ab00-a01e-11ea-901c-ecf9340eaeff.png)

borg info output

```
                       Original size      Compressed size    Deduplicated size
All archives:              486.82 GB            319.76 GB             30.29 GB

```

**Comment by m3nu** [comment]
Thanks for your concern, but Vorta uses the more detailed json-output that Borg provides. So the numbers won't match up. You can get json-output using the following command:

`borg info --json $ REPO_URL`

In detail, I decided to use:

- `total_size`: all the archives
- `unique_size`: after dedupe
- `unique_csize`: after compression

I chose those numbers because I find them more meaningful. I realize this is a personal decision. If  there are strong arguments for using different numbers, feel free to make your case or suggest a PR.

**Comment by caioau** [comment]
Thanks @m3nu ! Now everything makes sense! I been loving vorta! Keep up the awesome work!

**Comment by m3nu** [comment]
Thanks! Happy to be of service and make improvements where needed. 🙏
