### ISSUE TITLE
Add weekly option to scheduler tab

### ISSUE THREAD

**Issue by kwalker99** [borgbase/vorta#487]
Please can you add weekly backups to the scheduler...

**Comment by sudwhiwdh** [comment]
In theory, it should already be possible to set "Every 168 hours" (1 week) for a backup, right?
It's just not that user-friendly. On the other hand, a drop-down menu with additional options "Every week", "Every n months" might be too confusing at some point?

Maybe the option "Backup every x hours at y minutes past the hour" could be extended?

First idea: "Backup every x days, y hours, z minutes". And x can also be zero.
Second idea would be the drop down menu with additional entries.
I don't know what feels more natural for the user experience.

By the way: The wording " past the hour" sounds a bit complicated here.

**Comment by kwalker99** [comment]
Why not just add another radio button below daily...

Backup Weekly at <time> Day <day dropdown>

**Comment by kwalker99** [comment]
168 hours doesn't work correctly... in theory it should be 11/06/2020 or 06/11/2020 depending on date format...

What happens instead is:
**Next Backup:** 2020-06-08 01:00

**Comment by kwalker99** [comment]
by making this 240 hours, it is now 7 days from today, looks like a bug to me...

**Next Backup:** 2020-06-11 01:00

**Comment by m3nu** [comment]
Currently we support 2 timers: interval (backup every x days/hours) and fixed (backup at this hour every day).

If you enter >24 hours in the interval scheduler, it will get converted to days automatically. So `7*24 hours` would give you weekly backups.

The starting point != current time, which is what you observed above. This is not a bug.

If you are planning to add a weekly option, I'd add it to the fixed scheduler and make the time span a dropdown (daily, weekly, monthly). We use APScheduler internally, but don't want to expose every single option to keep it simple.

**Comment by sudwhiwdh** [comment]
> If you enter >24 hours in the interval scheduler, it will get converted to days automatically. So 7*24 hours would give you weekly backups.

7*24 would be = 168. Then why does it only seem to work with 240 hours? https://github.com/borgbase/vorta/issues/487#issuecomment-639005412

> but don't want to expose every single option to keep it simple.

:+1:

**Comment by stevenvandenbrandenstift** [comment]
It indeed seems to work with some values, 210 becomes about 4 days, so there seems to be a logic error in the conversion.

**Comment by samuel-w** [comment]
Here is my proposed UI design that replaces the daily and hourly options:
![uiProposal](https://user-images.githubusercontent.com/67625312/86838162-75466900-c065-11ea-8f5e-92b2d97127dd.png)

The starting at box label would update to have the same date as the next backup label

**Comment by m3nu** [comment]
I'm OK with adding the hour/day/week dropdown, but I find the *Starting At* field needlessly complicated. A user who wants backups every hour won't care when they start.

**Comment by sudwhiwdh** [comment]
> A user who wants backups every hour won't care when they start.

What about users who want to make sure that the backup starts at the hour the system was definitely booted?

**Comment by samuel-w** [comment]
There could be an option to run the backup if it was missed, so users don't have to worry about it. APScheduler does have an option for this https://apscheduler.readthedocs.io/en/stable/userguide.html#missed-job-executions-and-coalescing

Also, the starting at field has to include the time, even in hourly backups. For example, I want to set my backups to run every 12 hours, at 9 am/pm so that I have a backup at the start of the day and the end of the day. The selector can either be QDateTimeEdit, or QDateEdit, and QDateEdit doesn't provide enough granularity for this case.

**Comment by samuel-w** [comment]
I have been working on [a solution](https://github.com/samuel-w/vorta-1/tree/ScheduleFrequency), 
How should I handle conversions from old date system to new, since there are both hourly and daily options and one datetime field. Currently I have it set up to delete the old options without transfer, which I don't really like.
