### ISSUE TITLE
macOS: borg-macosx64 cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by cbenhagen** [borgbase/vorta#528]
**Describe the bug**
<img width="532" alt="Screenshot 2020-06-26 at 13 47 54" src="https://user-images.githubusercontent.com/814785/85853973-c75cd400-b7b3-11ea-9e07-75cfe0a88648.png">

**To Reproduce**
1. Open Vorta v0.6.26 or v0.6.24
2. See error

**Desktop**
 - OS: macOS Catalina 10.15.5 (19F101)

**Comment by m3nu** [comment]
This is how macOS works and it was already discussed in detail in a Borg issue. You have those options:

1. Authorize Borg to run by allowing it in Preferences > Security or by right click > open. There will still be a delay due to Apple validation each unpacked lib.
2. Uninstall Borg and use the signed Borg version we ship together with 

This should solve it, but feel free to check back if not. In the meanwhile I still close this issue, since it’s not related to Vorta.
