### ISSUE TITLE
Display Borg Progress data, different progress indicator

### ISSUE THREAD

**Issue by XXXBold** [borgbase/vorta#594]
**Is your feature request related to a problem? Please describe.**
It's very annoying when one runs a bigger backup, which will take some time, and there's absolutely no visible progress and ETA.

**Describe the solution you'd like**
- Change the progress bar on the "Repository" tab to actually show the progress in percent. For an easy solution, simply count the files, ignoring their size, that's better than it is now.
- Add status text, containing the following: Current speed, bytes copied, bytes left, and depending on the speed, give an ETA (Yes, this might be inaccurate, I'm aware of that)

Disclaimer:
I'm not familiar with the borg API, so probably there's no (easy) way to get progress/files count/data sizes etc. If so, maybe some changes could be made to borg first?

**Describe alternatives you've considered**
Can't find one

**Comment by samuel-w** [comment]
Currently borg does have a `--progress` option, but it displays a bar per file, not for the whole backup. 

There is no way to get a whole backup progress bar I believe, due to the nature of de-duplicating backups (no way to tell how many files are changed without multiple passes).

**Comment by ThomasWaldmann** [comment]
There is no ETA support in borg and likely there never will be. https://xkcd.com/612/

**Comment by XXXBold** [comment]
I understand that it's not trivial/possible to determine the targets datasize.

But the file list is available, is it, so the progress bar could be based on the current file count (processed/left) I think?

**Comment by ThomasWaldmann** [comment]
borg --progress tells how much it already processed (this is also available in a json format), but it does not predict the future (like telling how much is still coming, compute an ETA).

**Comment by XXXBold** [comment]
So I think this can be used than to show the current progress (ETA isn't that important imo)

**Comment by SergioRAgostinho** [comment]
> So I think this can be used than to show the current progress (ETA isn't that important imo)

Let me reinforce support for this idea. If possible, to bring the same information borg already reports in the terminal when `--progress` is specified, but displayed it here, as the backup takes place.
![Screenshot from 2020-09-02 21-11-43](https://user-images.githubusercontent.com/1709142/92026207-f61d9a80-ed60-11ea-83f0-678644446802.png)

**Comment by m3nu** [comment]
There is another open issue suggesting to calculate the size of each backup source folder.

Can we see the *processed* or *uploaded* files with `--progress`? If it's the former, we could use that for a rough progress report.

**Comment by ThomasWaldmann** [comment]
Due to deduplication / unchanged file detection that is not a good way. With "size already processed" people will try to extrapolate ETA from that (and will be wrong, potentially very wrong). A huge file/folder can go fast, while a much smaller file/folder can take long.

What maybe could work is showing a "n files already processed" because people know files have different sizes and will maybe not try to extrapolate ETA from that. Would not invest the time to determine total number of files though, takes extra time and can be wrong anyway if it is not a snapshot, but a changing fs.

Other factors are fluctuations in local speed (due to other loads on system, overhead), remote speed (same) and connection speed.
So a good progress indicator or ETA is rather hopeless and implementing a bad one will just cause a lot of disappointment/complaints, see windows explorer. :-)

**Comment by m3nu** [comment]
Listen to the expert, @SergioRAgostinho 😄

Since most backups run automated I also don't see it as critical feature. For initial backups, we show the file currently processing. That's what I generally use as estimate.

We *could* consider replacing the current animated progress bar with a different indicator that doesn't imply any ETA.

**Comment by SergioRAgostinho** [comment]
I see this is a contentious topic. 

> Can we see the _processed_ or _uploaded_ files with `--progress`?

Yes. It reports a monotonic counter of the data that has been processed. One last time and just to be very clear: I'm not asking to make ETA predictions of any sort or calculate the size of the full backup. I agree with the arguments made here with respect to that. I'm just asking to display the same information `--progress` displays.

> Since most backups run automated I also don't see it as critical feature. For initial backups, we show the file currently processing. That's what I generally use as estimate.

In that, I completely agree. It is in the "nice-to-have" ballpark. I had the experience with a couple of really large files and the report from  `--progress` provided a good sanity check on whether any progress was taking place. Something very useful when the user is no longer sure if reading data from the hard-drive is actually taking place e.g., in the case of faulty hdds.

I think this summarizes the whole point: it provides quantitative confirmation that progress is being made, and it does so more atomically than reporting the current file being processed. It only provides value in interactive use, not in automation.

I was really hoping that the benefit of having this info would be sufficient to beat the stigma of "people creating false expectations".

**Comment by m3nu** [comment]
That's reasonable. Let's keep this as an idea here to keep track.

**Comment by m3nu** [comment]
While we can't give a % estimate, @SergioRAgostinho implemented displaying the progress reported by Borg in #615.
