### ISSUE TITLE
Link to bug report does not open in flatpak

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#610]
**Describe the bug**
See title, this only affects the flatpak version

**To Reproduce**
1. Go to misc tab
2. Click "Report a bug"
Github page does not pop up

This does not happen in the pip version

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Vorta: 0.6.26

**Comment by ktosiek** [comment]
I couldn't reproduce this on Ubuntu 20.04 with neither current flathub build nor a local build of Vorta master.

What happens when you run `flatpak enter com.borgbase.Vorta env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus xdg-open https://example.com`? (the `env` part is required to work around https://github.com/flatpak/flatpak/issues/3820, but if you can see notifications then Vorta can connect to DBus).

**Comment by samuel-w** [comment]
I restarted and it works. Yay bugs!
