### ISSUE TITLE
[BUG] Scheduling by hour is not working right

### ISSUE THREAD

**Issue by teemue** [borgbase/vorta#659]
When setting interval for backups by hour, the time for next backup is not calculated right. GIF attached for example:

![Sep-18-2020 17-05-56](https://user-images.githubusercontent.com/317905/93607264-c5309d00-f9d1-11ea-9c66-7c327e73b1dc.gif)

- OS: macOS 10.15.6
- Vorta version: 0.7.1
- Installed from: brew

**Comment by m3nu** [comment]
Probably not a Vorta issue, since we use [APScheduler](https://apscheduler.readthedocs.io/en/stable/) for this functionality. You probably want to open your issue there. Vorta doesn't implement any scheduling functionality itself.

Also note that Cron doesn't necessarily calculate the next backup time from the current time. Maybe this is what's causing confusion?

**Comment by samuel-w** [comment]
I think the issue is not APScheduler or Vorta related. It's caused by the cron timer logic working something like this:
Take start of current day
Add time offset until it exceeds current time
If the date is set to tomorrow, then start at start of current day. Otherwise, set it to the calculated time.

And by start of current day I mean 12:00 am.

**Comment by teemue** [comment]
Thanks. Let's hope so @samuel-w  :)
