### ISSUE TITLE
extract: file selection

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#69]
if you select some directory, the stuff below it stays unselected (on the gui).
but of course it is extracted.

**Comment by m3nu** [comment]
I can only partially solve this because it would be too confusing to exclude child-folders when the top-level folder is selected.

For now, child folders will inherit the parent folder's selection status. I also added a note about this behavior. If this becomes a large problem, an exclusion-list could be built from items who have their parent selected, but are unselected themselves.

<img width="764" alt="screenshot 2018-12-05 at 15 01 16" src="https://user-images.githubusercontent.com/3916435/49495749-05776780-f89f-11e8-93e9-3c959a3d70ef.png">
