### ISSUE TITLE
Working version for the Raspberry Pi4 (Buster)

### ISSUE THREAD

**Issue by cw123hb** [borgbase/vorta#694]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by samuel-w** [comment]
Vorta is designed to be a desktop backup solution. Are you using the RPi as a desktop? Otherwise, something like https://github.com/witten/borgmatic or just regular borgbackup might be better fit for your use case.

**Comment by cw123hb** [comment]
I am using Pi as a Desktop, well functioning at that.

**Comment by samuel-w** [comment]
You have an installation issue, caused by PyQt5. Nothing we can do, since the PyQt5 packages provided by Raspbian are broken as well, and the packages in general provided by Raspbian are super out of date. See https://github.com/borgbase/vorta.borgbase.com/pull/14#issue-488851459 for more details.

If you really want to use a RPi as a desktop, the flatpak package, or use some other more up to date OS like Ubuntu https://ubuntu.com/download/raspberry-pi.

**Comment by sten0** [comment]
@cw123hb Vorta is on track for inclusion into Debian 11 (bullseye), and thus the next stable release of Raspian.  If Raspbian has a development release based off of Debian testing or sid, I'd encourage you to switch to it in late January or later.  One downside of following a development release may be SD card wear due to frequent updates.  PyQT5 builds in Debian are good on arm64, armel, and armhf, and should be good in the next Raspbian release.
