### ISSUE TITLE
How does Vorta compare to Bup/Kup and BackInTime? Please add a comparison of features/functionality

### ISSUE THREAD

**Issue by mYnDstrEAm** [borgbase/vorta#705]
**Is your feature request related to a problem? Please describe.**
I couldn't find a clear and useful comparison of Borg/Vorta with [Bup/the Qt GUI Kup](https://github.com/bup/bup) and [BackInTime](https://github.com/bit-team/backintime/). These seem to be the three best FOSS backup software with a Qt GUI. Such a comparison would be useful for:
* users to find out whether Vorta is the adequate and/or best solution
* other developers to identify which Vorta features to add to their software
* developers of Vorta to identify which features other similar software has but Vorta lacks so that it can be added to make Vorta the best solution, allowing for all functionality of other software

**Describe the solution you'd like**
It would be good if a separate website and/or [the Vorta website](https://vorta.borgbase.com/) had a comparison of functionality/features of Vorta in direct comparison with (at least) these two other software. This comparison should probably be linked to either directly from "_Why is this great?_" in the readme or be findable at the link in "_Learn more on Vorta's website._"

Maybe this would be more appropriate at https://github.com/borgbase/docs.borgbase.com

* _BackInTime_ is great software but its development currently seems to be inactive. I suggested Vorta as an alternative to it here: https://github.com/bit-team/backintime/issues/1092#issuecomment-664042558 I'm mostly interested in how Vorta differs from it and which features BackInTime offers that Vorta currently does not have.
* _Kup_ is a Qt GUI for Bup and it seems to integrate nicely into KDE and, unlike Vorta, is in Debian's repos. However Bup isn't in the repos of latest Debian (only in older versions).

**Comment by m3nu** [comment]
Yeah, this could be added to the docs. But no problem to discuss it here and later do a PR there.

**Comment by Golddouble** [comment]
Here are some Ideas what could be included in this comparison:
(Maybe also LuckyBackup and "Deja Dup" could be included in this comparison. I know, that this are more sync programs, but nevertheless, actually they are also used to backup data)
1. How much time it takes to make a full backup of a sample of "folders and files".
2. How much time it takes to make something that feels like an incremental Backup.
3. How much place a fill backup takes with default settings.
4. How much place something takes that feels like a incremental backup.
5. Is it possible to brows through the files of the latest backup-archive?
6. Is it possible to browse through the files in any incremental backup-archive?
7. Can we recover single files or single folders from the latest backup or only the whole backup?
8. Can we recover single files or single folders from any incremental backup or only the whole backup?
9. How can I recover the whole home folder? Can I recover the whole home folder of the same system I am using at the moment? Or must I use a live system? Or something else?
10. Is there a function to verify my backups?
11. Is there an option that automatically very files my backup after each incremental backup.
12. Can I verify only the latest incremental backup or do I have to verify always all backups of a repository
13. Can I encrypt my archive
14. Can I use a password
15. Can I delete any particular "incremental Backup" or only the latest?
16. Does it support differential Backups
17. When I file has changed since the latest backup, does then the backup program always save the whole file new or only parts of this file.
18. Is the backup program designed to backup only "home" or "only "Root" or both.
19. Can we define exclusions rules
20. Is there an assistand for creating exclusion rules?
21. Is there a GUI for this program
22. Is the program actively supported (help)
23. Has it a good documentation?
24. For the recovery process: Can we define rules, if files that are already in the target should be deleted or kept. Alreday but only if it is newer. And other "sync rules".

**Comment by Golddouble** [comment]
This is a comparison between Borg, Restic, Arq 5, Duplicacy, Duplicati:
https://forum.duplicati.com/t/big-comparison-borg-vs-restic-vs-arq-5-vs-duplicacy-vs-duplicati/9952

**Comment by m3nu** [comment]
Cool. Borg is actually quite fast. I do wonder what's _Pcloud Virtual_ and if it runs Borg remotely. They should repeat it with BorgBase or another SSH-based backend.

**Comment by mat-m** [comment]
pCloud virtual is a fuse FS which caches the cloud data.

` fusermount -o rw,nosuid,nodev,auto_unmount,fsname=pCloud.fs,nonempty -- /home/me/pCloudDrive`
