### ISSUE TITLE
Scheduler issues after hibernation (macOS)

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#8]
As reported by @adamluk, the scheduler will skip at least one run if they are missed during hibernation.

**Comment by m3nu** [comment]
Suggested solution:
- listen for `NSWorkspaceDidWakeNotification`
- call APScheduler `wakeup()`

**Comment by m3nu** [comment]
Closing since it doesn't seem to occur any more.

**Comment by m3nu** [comment]
ok. reopening.

**Comment by adamluk** [comment]
Interestingly I have just checked and the scheduler has now updated. I presume it is making a call every x minutes to update next scheduled backup?

**Comment by m3nu** [comment]
Depends on where you look:

- the time on the schedule tab is currently only updated when re-opening the window or applying settings.
- time in the tray icon is updated every time the tray is opened.

If the problem is the outdated time on the Schedule-tab, then I can fix that easily.

**Comment by adamluk** [comment]
![screenshot 2018-11-17 at 13 03 15](https://user-images.githubusercontent.com/9057461/48661424-762e1f80-ea69-11e8-8e86-d27f935a4d8c.png)
![screenshot 2018-11-17 at 13 03 59 1](https://user-images.githubusercontent.com/9057461/48661425-762e1f80-ea69-11e8-8733-7b910483ca61.png)

It seems that the time in the tray icon does update - although not immediately as per screenshots.

This seems to be a visual bug?

**Comment by adamluk** [comment]
Just as an example the 13:59 backup was missed due to the computer sleeping. I woke the computer up at 14:00 - the backup did not run and the time in the tray icon did not update to display "Next Task: 14:59" until 14:10 , meaning it took approximately 10 minutes for the tray icon to be updated.

The time on the schedule tab is still showing as Next Backup 12:59, despite this being missed and the tray icon showing "Next Task: 14:59". This is despite the Vorta window being closed and then re-opened from the tray icon. If I exit and then re-launched Vorta the time in the schedule tab updates.

Hope that helps?

**Comment by m3nu** [comment]
Yeah. I'll look into it again. I already had a suggested solution.

**Comment by m3nu** [comment]
I looked into this and catching the wakeup-signal from macOS isn't easy and would introduce a lot of platform-specific code.

But I did some other things to improve this issue:

- when clicking the tray icon, the scheduler will be woken up and the job should either run immediately (if it wasn't missed by more then X minutes) or show the correct time.
- the time in the scheduler-tab now updates when changing the tab.
- the time in the scheduler-tab now updates after a backup has finished running.
