### ISSUE TITLE
vorta 0.7.4 broken with PyQT 5.15.3 on Arch

### ISSUE THREAD

**Issue by bjo81** [borgbase/vorta#896]
**Describe the bug**
pkg_resources.DistributionNotFound: The 'PyQt5-Qt>=5.15' distribution was not found and is required by pyqt5

**To Reproduce**
start vorta after upgrading python-pyqt5 from 5.15.2 to 5.15.3

**Environment**
- OS: Arch Linux
- Vorta version: 0.7.4 (also reported with 0.7.3)
- Installed from: AUR 

**Additional context**
Further discussion here: https://aur.archlinux.org/packages/vorta/

**Comment by m3nu** [comment]
There was a change in the way PyQt5 is packages. If you compare 5.15.2 and 5.15.3, you see a new dependency `PyQt5-Qt`.

```
$ diff PyQt5-5.15.*/PKG-INFO
3,4c3,4
< Version: 5.15.2
< Requires-Python: >=3.5
---
> Version: 5.15.3
> Requires-Python: >=3.6
9a10
> Requires-Dist: PyQt5-Qt (>=5.15)
```

So they now ship some Qt binaries via PyPi? Arch already ships those bins in other packages. So this package is not required for you. BUT your `python-pyqt5` still references it as dependency:

```
head -n11 /usr/lib/python3.9/site-packages/PyQt5-5.15.3.dist-info/METADATA
Metadata-Version: 2.1
Name: PyQt5
Version: 5.15.3
Requires-Python: >=3.6
Summary: Python bindings for the Qt cross platform application toolkit
Home-Page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-Email: info@riverbankcomputing.com
License: GPL v3
Requires-Dist: PyQt5-sip (>=12.8, <13)
Requires-Dist: PyQt5-Qt (>=5.15)
```

So you may need to remove the last line in Arch's `python-pyqt5` pkg to resolve this error:

`pkg_resources.DistributionNotFound: The 'PyQt5-Qt>=5.15' distribution was not found and is required by pyqt5`

Vorta is just unlucky because importing `pkg_resources` exposes the issue, but it could happen with other applications too.

**Comment by bjo81** [comment]
Thanks for pointing this out, the Arch package has been fixed now as it lead also to issues with other applications: https://bugs.archlinux.org/task/69802
